spring:
  application:
    name:
      security

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/security}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
server:
  port: ${PORT:8080}

